[build]
  publish = "."
  command = "echo 'No build command'"

[functions]
  directory = "netlify/functions"
  included_files = ["app.py", "requirements.txt", "js/**", "css/**", "assets/**", "index.html"]

# Specific rule for API with FORCE to prevent fallback
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"  # Use :splat to pass the rest of the path
  status = 200
  force = true

# Fallback for everything else to index.html (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
